export function authHtml() {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#10120f"><title>Unlock Artifact Vault</title>
<style>:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;background:#10120f;color:#eeeede}body{margin:0;min-height:100dvh;display:grid;place-items:center;padding:24px;box-sizing:border-box}.card{width:min(100%,400px);border:1px solid #495245;background:#151914;padding:28px}h1{font-size:25px;letter-spacing:.07em;margin:0 0 10px;text-transform:uppercase}p{color:#aab09e;line-height:1.5}input,button{box-sizing:border-box;width:100%;font:inherit;padding:13px;margin-top:12px}input{border:1px solid #495245;background:#10120f;color:#eeeede}button{border:0;background:#c9d69e;color:#10120f;cursor:pointer}.status{min-height:1.5em;color:#c9d69e;font-size:13px}</style></head>
<body><main class="card"><h1>Artifact Vault</h1><p id="description">Unlock with your device passkey.</p><input id="setup-token" type="password" autocomplete="off" placeholder="Setup code" hidden><button id="action" type="button">Unlock with passkey</button><p class="status" id="status" aria-live="polite"></p></main>
<script src="/auth/webauthn.js"></script><script>
const action=document.querySelector('#action'),status=document.querySelector('#status'),description=document.querySelector('#description'),setupToken=document.querySelector('#setup-token');
let configured=false;
async function request(path, options={}){const headers={...options.headers};if(options.body)headers['Content-Type']='application/json';const response=await fetch(path,{headers,...options});const body=await response.json();if(!response.ok)throw new Error(body.error||'Request failed');return body}
async function load(){const state=await request('/auth/status');configured=state.configured;if(!configured){description.textContent='Set up this vault with Face ID or your device passkey.';setupToken.hidden=false;action.textContent='Create passkey'}}
action.addEventListener('click',async()=>{action.disabled=true;status.textContent='Waiting for your device…';try{if(configured){const {options,challengeId}=await request('/auth/login/options',{method:'POST'});const response=await SimpleWebAuthnBrowser.startAuthentication({optionsJSON:options});await request('/auth/login/verify',{method:'POST',body:JSON.stringify({response,challengeId})})}else{const token=setupToken.value;const {options,challengeId}=await request('/auth/register/options',{method:'POST',headers:{'X-Setup-Token':token}});const response=await SimpleWebAuthnBrowser.startRegistration({optionsJSON:options});await request('/auth/register/verify',{method:'POST',body:JSON.stringify({response,challengeId})})}location.replace('/')}catch(error){status.textContent=error.message}finally{action.disabled=false}});load().catch(error=>status.textContent=error.message);
</script></body></html>`;
}
